baseURL = "https://jethromay.com/"
languageCode = "en-us"
title = "Jethro May"

enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[author]
    name = "Jethro May"

[params]
    title = "Full-stack web developer & writer."
    description = "Jethro May is a full-stack web developer & writer with a passion for Laravel."

[permalinks]
    posts = "/posts/:slug"
    page = "/:slug/"
