baseURL = "https://jethromay.com/"
languageCode = "en-us"
title = "Jethro May"

enableGitInfo = true

[params]
    author = "Jethro May"
    title = "Full-stack web developer & writer."
    description = "Jethro May is a full-stack web developer & writer with a passion for Laravel."

[taxonomies]
   tag = "tags"

[permalinks]
    posts = "/posts/:slug"
    page = "/:slug/"
