baseURL = "https://jethromay.com/"
languageCode = "en-us"
title = "Jethro May"

enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[author]
    name = "Jethro May"

[params]
    title = "Full-stack web developer."
    description = "Jethro May is a full-stack web developer currently living and working in sunny South Africa."

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/posts/:slug"
    page = "/:slug/"
