baseURL = "https://jethromay.com/"
languageCode = "en-us"
title = "Jethro May"

enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[author]
    name = "Jethro May"

[params]
    title = "Full-Stack PHP Developer"
    description = "Jethro May is a full-stack PHP developer currently living and working in South Africa."

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/posts/:slug"
    page = "/:slug/"
