baseURL = "https://jethromay.com/"
languageCode = "en-us"
title = "Jethro May"

enableGitInfo = true

[taxonomies]
   tags = "tags"

[permalinks]
    posts = "/posts/:slug"

[author]
    name = "Jethro May"
